Gestion_RecursoHumano/Controllers/GestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Unity;
using Gestion_RecursoHumano.Repositories;
using Gestion_RecursoHumano.Models;

namespace Gestion_RecursoHumano.Controllers
{
    public class GestionController : Controller
    {
        #region Repositories
        [Dependency]
        public IEmpleadoRepository empleadoRepository { get; set; }
        #endregion

        public ActionResult Index()
        {
            return View();
        }

        //funcion para agregar un nuevo empleado
        public ActionResult NuevoEmpleado(Empleado empleado)
        {
            //esta linea guarda el empleado recibido por el controller desde la vista
            this.empleadoRepository.Add(empleado);

            //esta linea hace el save, es decir guarda los cambios
            this.empleadoRepository.Save();

            //esta linea redirige el controller la metodo Index() del controller
            return RedirectToAction("Index");
        }

        //para actualizar un empleado
        public ActionResult ActualizarEmpleado(Empleado empleado)
        {
            if(this.empleadoRepository.Exist(x => x.Id == empleado.Id))
            {
                this.empleadoRepository.Update(empleado);
                this.empleadoRepository.Save();
            }
            return RedirectToAction("Index");
        }

        //funcion para buscar un empleado
        public ActionResult BuscarEmpleado(string textoBusqueda)
        {
            //esta linea busca al empleado por el nombre o por el apellido
            var empleado = this.empleadoRepository.Select(x => 
            x.Nombre_Empleado.Contains(textoBusqueda)
            || x.Apellido.Contains(textoBusqueda)
            );
            return RedirectToAction("Index", empleado);
        }

        public ActionResult RegistrarEmpleado()
        {

            return View();
        }

    }
}

Gestion_RecursoHumano/Controllers/InformeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_RecursoHumano.Controllers
{
    public class InformeController : Controller
    {
        // GET: Informe
        public ActionResult Index()
        {
            return View();
        }
    }
}

Gestion_RecursoHumano/Controllers/ServiciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Gestion_RecursoHumano.Controllers
{
    public class ServiciosController : Controller
    {
        // GET: Servicios
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Gestion_RecursoHumano/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <style>
        .dropdown:hover > .dropdown-menu {
            display: block;
            background-color: #121111;
            
            cursor: pointer;
        }

        ul li {
            color: blue;
        }

        /*.dropdown .dropdown-menu > li > .submenu {
            display: block;
            float: left;
            background-color: white;
            cursor: pointer;
        }*/

    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestión Recurso Humano", "Index", "Gestion", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*Menu empleados*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Empleados<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink("Registrar", "RegistrarEmpleado", "Gestion")</li>
                            <li> @Html.ActionLink("Registrar Salida", "RegistrarSalida", "Gestion")</li>
                            
                                @*<li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Empleados<span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li> @Html.ActionLink("Registrar", "Index", "GestionController")</li>
                                        <li> @Html.ActionLink("Salida", "About", "GestionController")</li>
                                        <li> @Html.ActionLink("Registrar Vacaciones", "Contact", "GestionController")</li>
                                        <li> @Html.ActionLink("Registrar Permiso", "Contact", "GestionController")</li>
                                        <li> @Html.ActionLink("Registrar Licencia", "Contact", "GestionController")</li>
                                    </ul>
                                </li>*@
                            <li> @Html.ActionLink("Registrar Permiso", "RegistrarPermiso", "Gestion")</li>
                            <li> @Html.ActionLink("Registrar Licencia", "RegistrarLicencia", "Gestion")</li>
                        </ul>
                    </li>

                    @*Menu Servicios*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Servicios<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink("Generar Nomina", "GenerarNomina", "Servicios")</li>

                            @*<li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Empleados<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li> @Html.ActionLink("Registrar", "Index", "GestionController")</li>
                                    <li> @Html.ActionLink("Salida", "About", "GestionController")</li>
                                    <li> @Html.ActionLink("Registrar Vacaciones", "Contact", "GestionController")</li>
                                    <li> @Html.ActionLink("Registrar Permiso", "Contact", "GestionController")</li>
                                    <li> @Html.ActionLink("Registrar Licencia", "Contact", "GestionController")</li>
                                </ul>
                            </li>*@

                        </ul>
                    </li>

                    @*Menu *@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Informes <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li> @Html.ActionLink("Nomina", "Informe_Nomina", "Informe")</li>
                            <li> @Html.ActionLink("Empleados Activos", "Informe_Activos", "Informe")</li>
                            <li> @Html.ActionLink("Empleados Inactivos", "Informe_Inactivos", "Informe")</li>
                            <li> @Html.ActionLink("Listado Departamentos", "Informe_Departamentos", "Informe")</li>
                            <li> @Html.ActionLink("Listado Cargos", "Informe_Cargos", "Informe")</li>
                            <li> @Html.ActionLink("Entrada Empleados por Mes", "Informe_Entrada_Mes", "Informe")</li>
                            <li> @Html.ActionLink("Salida Empleados por Mes", "Informe_Salida_Mes", "Informe")</li>
                            <li> @Html.ActionLink("Permisos", "Informe_Permisos", "Informe")</li>
                            
                            @*<li role="separator" class="divider"></li>*@
                          
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Acerca De", "About", "Gestion")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>